config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"
  resources :posts

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end
  def new
    @post = Post.new
  end
  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end


  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to posts_path
    else
      render :update
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end


  private
  def post_params
    params.require(:post).permit(:title, :content, :level, :start_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TurboFramesFirst</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_post.html.erb
<% frame_id = dom_id(post, "title_to_turbo_frame")%>
<%= turbo_frame_tag frame_id do %>
  <%= link_to post.title, edit_post_path(post) %>
  <%= button_to "Delete", post_path(post), method: :delete %>
<% end %>

app/views/posts/edit.html.erb
<% frame_id = dom_id(@post, "title_to_turbo_frame")%>
<%= turbo_frame_tag frame_id do %>
 <%= form_with(model: @post) do |form| %>
    <%= form.text_field :title %>
    <%= form.button "Save" %>
    <%= link_to "Cancel", @post %>
  <% end %>
<% end %>

app/views/posts/index.html.erb
<h1>Tous les posts !</h1>
<%= render  partial: "post", collection: @posts %>

app/views/posts/show.html.erb
<%= form_with model: @post do |form| %>
  <h2><%= @post.title %></h2>
  <br>
  content: <%= @post.content %>
<% end %>